Repository splunk-soar-connectors/fuseboxutility, pull requests merged in 2022-07, with the labels that each got.

#2 PAPP-26538: Initial commit with developer checklist
  LICENSE
  README.html
  __init__.py
  fusebox.json
  fusebox_connector.py
  logo_fusebox.svg
  logo_fusebox_dark.svg
  release_notes/unreleased.md
  requirements.txt
  tox.ini
Labels: external-contributor, developer-supported, PAPP-26538

#4 Fixed code issues from previous update
  fusebox_connector.py
Labels: external-contributor, developer-supported, PAPP-26686

#8 Updated release version of md file
  release_notes/1.0.2.md
Labels: developer-supported
